### ISSUE TITLE
GenMAPP export fails due to missing attribute in latest XSD schema

### ISSUE THREAD

**Issue by dondi** [lmu-bioinformatics/xmlpipedb#1]
The latest XSD schema contains a change that breaks current GenMAPP Builder export code. The query in question that breaks is:

```sql
    select evidencedstringtype.value
        from commenttype inner join entrytype_comment
        on (entrytype_comment_hjchildid = commenttype.hjid)
        inner join evidencedstringtype on (text = evidencedstringtype.hjid)
        where type = 'function'
            and entrytype_comment_hjid = ?;
```

...where `?` represents some entry ID. The error is:

    column "text" does not exist

Because the new schema no longer has a `text` attribute in the `commenttype` table.

This query needs to be updated to line up with the latest XSD schema.

**Comment by kdahlquist** [comment]
Verified that export finishes with draft release of gmb2b85.
