### ISSUE TITLE
Fix link out for GO, Pfam, and EnsemblBacteria in Systems table

### ISSUE THREAD

**Issue by kdahlquist** [lmu-bioinformatics/xmlpipedb#10]
I'm testing the Backpage links for the Vibrio export.  The link for GO is going to the wrong page, stay tuned for how to fix it.

**Comment by kdahlquist** [comment]
Pfam and EnsemblBacteria also have issues, stay tuned for how to fix it.

**Comment by kdahlquist** [comment]
If I were to push a fix to this directly to GitHub, where would I put it?  Which branch?  Where is this file anyway in the code?  I think for the sake of expediency, I will need to tell @dondi the changes and have you make them.

**Comment by kdahlquist** [comment]
For GO terms, the new Link out should be:

http://amigo.geneontology.org/amigo/term/GO:~

For example: http://amigo.geneontology.org/amigo/term/GO:0061621

In our gdb, the "GO:" has been stripped out of the ID column, so I'm thinking that the tilde has to go after the ":", right?

**Comment by kdahlquist** [comment]
For Pfam the new link out should be:

http://pfam.xfam.org/family/~

For example: http://pfam.xfam.org/family/PF00587

**Comment by kdahlquist** [comment]
For EnsemblBacteria, the new link out should be:

http://bacteria.ensembl.org/Multi/Search/Results?species=all;idx=;q=~;site=ensemblunit

For example: http://bacteria.ensembl.org/Multi/Search/Results?species=all;idx=;q=AAF96469;site=ensemblunit

We should also change the link out for OrderedLocusNames for Vibrio to this EnsemblBacteria on.  The TIGR CMR is no longer actually online that I can tell.

I'm reassigning this to @dondi .

**Comment by dondi** [comment]
Sounds great, I will add/modify these link-outs tonight, and release a new build-5 after that.

Just to answer the earlier question, the changes can be submitted (though not tested) by editing this file directly:

https://github.com/lmu-bioinformatics/xmlpipedb/blob/access-64-bit/gmbuilder/src/edu/lmu/xmlpipedb/gmbuilder/databasetoolkit/profiles/VibrioCholeraeUniprotSpeciesProfile.java

The branch where all of this work is currently happening is `access-64-bit`. (as you know it has grown in scope quite a bit from just 64-bit, but the name has stuck so far)

**Comment by dondi** [comment]
Follow-up question...are these linkout changes universal, or specific to *V. cholerae*? If they are universal, they would go in the database template file. If they are specific, they would go in the Java species profile.

**Comment by kdahlquist** [comment]
You answered your own question.  They are universal and need to go into the database template file.  The link for OrderedLocusNames fro Vibrio needs to be changed in the profile.

**Comment by dondi** [comment]
OK, this has been changed. I did an export, loaded the result into GenMAPP, then did a quick back page lookup. The links worked.

**Comment by dondi** [comment]
Merged into `master` with pull request #17.
