### ISSUE TITLE
Change linkout for OrderedLocusNames for Vibrio profile

### ISSUE THREAD

**Issue by kdahlquist** [lmu-bioinformatics/xmlpipedb#11]
Stay tuned for where this should link to now...probably EnsemblBacteria, but I need to double-check that one as well.

**Comment by kdahlquist** [comment]
I answered this in issue #10.  It should definitely go to EnsemblBacterial since CMR is no longer supported or even online.

**Comment by dondi** [comment]
Merged into master with pull request #17.
