### ISSUE TITLE
review all species profiles for link outs to CMR and change to EnsemblBacteria

### ISSUE THREAD

**Issue by kdahlquist** [lmu-bioinformatics/xmlpipedb#16]
The JCVI CMR is no longer supported (or even available).  We should review all of the custom species profiles for link outs to CMR and replace them with link outs to EnsemblBacteria.

**Comment by dondi** [comment]
This turned out to be fairly straightforward—a search showed that *H. pylori* and *S. typhimurium* were the only two other organisms that linked to CMR. These were changed to EnsemblBacteria although not tested for now. The fixes reside in **build-5** onwards.

**Comment by dondi** [comment]
Merged into `master` via pull request #17.
