### ISSUE TITLE
migrate the rest of the gdb's from SourceForge to GitHub

### ISSUE THREAD

**Issue by kdahlquist** [lmu-bioinformatics/xmlpipedb#21]
So far, only S. aureus and V. cholerae have had their gdb's migrated to GitHub.  We should migrate the remainder of the released gdb's.

**Comment by dondi** [comment]
All files migrated and visible in the `gene-db-upload` branch. This can be looked at alongside issue #27 in order to make a final decision on naming. For now they were uploaded under the prior scheme, which mirrors the original release structure.

**Comment by kdahlquist** [comment]
I've verfied that they are there on the gene-db-upload branch.  I think I don't want to mess around with the naming right now #27  because there are other more important things to do.  I'm going to close this.
