### ISSUE TITLE
move source for XMLPipeDB web site to GitHub repository?

### ISSUE THREAD

**Issue by kdahlquist** [lmu-bioinformatics/xmlpipedb#22]
Is it possible to move the source for the XMLPipeDB web site to the GitHub repository?  That way multiple members of the group can edit, not just @dondi .

**Comment by dondi** [comment]
It turns out that the source for the site is now in GitHub as well. @kdahlquist can edit those as needed on a beta branch and @dondi will take care of shifting the site-building system to the GitHub copy.
