### ISSUE TITLE
customizations need to be completed for Shewanella profile

### ISSUE THREAD

**Issue by kdahlquist** [lmu-bioinformatics/xmlpipedb#24]
It appears that the customizations to the species profile for Shewanella were not completed.

* the species name is not appearing for OrderedLocusNames in the species field
* no linkout for OrderedLocusNames

According to @dondi , they are there in the code, but got commented out at some point.  This needs to be fixed and a new export run so that we can release the gdb.

**Comment by dondi** [comment]
It turns out that this customization was overwritten by [this commit](https://github.com/lmu-bioinformatics/xmlpipedb/commit/270671fcc1cf2e5698f6a7210d6b4fc2572a3d28). The deleted code just needs to be restored and the customizations should come back.

**Comment by dondi** [comment]
This has been fixed, and the draft release has been revised to 3.0.1-build-2.
