### ISSUE TITLE
Branch clean-up

### ISSUE THREAD

**Issue by kdahlquist** [lmu-bioinformatics/xmlpipedb#31]
I just met with @NAnguiano this morning to go over BIOL 367T stuff.  She's going to do a Vibrio export this week as make-up for the Week 9 assignment.  

Once the gdb passes quality checks, I want her to upload it to the repository, but I think we need to do some branch clean-up first.

It looks like we can safely delete the b-pertussis, s-oneidensis, s-flexneri, and c-cenocepacia branches because they were merged into master.  I think the fall2015 branch has also been merged and is no longer needed.

That leaves the gene-db-upload and readme branches that have changes not yet merged into master.  

I think we should go ahead and merge them both and then delete the readme branch (which was what I was using to create a markdown version of the readme files.)  This would then just leave the master and gene-db-upload branches.  @NAnguiano could then upload any new gdb's to this branch as the dev branch for new gdb's.

I think I might be able to take care of this, after @dondi agrees with the plan.

**Comment by dondi** [comment]
Branches have been deleted and the readme branch has a pull request: https://github.com/lmu-bioinformatics/xmlpipedb/pull/32 This makes it easy to look at the changes that will come in (in case you want to double-check). Otherwise, clicking _Merge pull request_ will do the merge or if you prefer that I do it, just let me know.

**Comment by kdahlquist** [comment]
OK, I merged readme into master and deleted the readme branch.

Now, what about the gene-db-upload branch?  I'd like to merge it and delete it as well.

Then any new development can go on in a new beta branch from master, if needed.

**Comment by kdahlquist** [comment]
@NAnguiano has merged the gene-db-upload branch into master and then deleted it, so we have just a single branch at the moment.  She and I are going to do a little more rearranging of folders/files on that branch before splitting of a new beta for new development #33.

**Comment by kdahlquist** [comment]
done.
