### ISSUE TITLE
GenMAPP Builder errors on importing recent GO obo-xml file

### ISSUE THREAD

**Issue by NAnguiano** [lmu-bioinformatics/xmlpipedb#34]
When importing the GO OBO-XML file into GenMAPP Builder, the file fails to import. 

This is the error returned: 
![errnull](https://cloud.githubusercontent.com/assets/6444156/18597436/eb433ae4-7c02-11e6-9058-008a3ec9ef4e.png)

This is the error log in the console:
![errlog](https://cloud.githubusercontent.com/assets/6444156/18597471/0f873d56-7c03-11e6-9a66-55f0a85ca659.png)

Using a GO OBO-XML file from a little under a year ago generates no errors.

**Comment by dondi** [comment]
Looks like the GO OBO schema has changed yet again. This will require an update to the GO library.

**Comment by NAnguiano** [comment]
I'm not sure if this is related to any file format changes or not, but I started this export at 12:26pm. It's 7:13pm currently and it's still running. The progress bar says 67%.

**Comment by kdahlquist** [comment]
Did this ever finish?  You can check the console log again to see if there is an error.

**Comment by kdahlquist** [comment]
After #31 and #33, @NAnguiano needs to get with @dondi to run the xsd-to-db and regenerate the GODB files.

There is some instruction on the SourceForge wiki here: http://xmlpipedb.sourceforge.net/wiki/index.php/Using_XSD-to-DB

Please create a wiki page on the GitHub wiki with these instructions and any additions you think are necessary as you work through the instructions.

For that matter, create a README.md folder in the xsd2db folder that also has the instructions.  We will work on moving the documentation over from the SourceForge wiki to here.

**Comment by NAnguiano** [comment]
I did the following:
1. Manually update the .dtd file in the repo to add in the new elements.
2. Run xsd2db on the new file.
4. Run godbpostprocessor.
5. Select .sql file and hbm file specified by the post processor. 
6. Build the .jar with the new sql and hbm files.
7. Replace godb.sql with the edited sql file.
8. replace godb.jar with the new jar file.
9. Run GMBuilder.

The obo-xml file no longer had a critical error after that. Further errors reported in Issue #41.

**Comment by kdahlquist** [comment]
@dondi, when you get a chance, can you look at what @NAnguiano posted to see if anything is left out?

**Comment by NAnguiano** [comment]
All errors related to the import of the obo-xml file appear to have been fixed. The new process I followed was:
1. Run xsd2db on the manually edited dtd file
2. Run godbpostprocessor.
3. Select .sql file and hbm file specified by the post processor. 
4. Build the .jar with the new sql and hbm files.
5. Replace godb.sql with the edited sql file.
6. replace godb.jar with the new jar file.
7. Copy the contents of the new godb.sql file and replace the corresponding section in gmbuilder.sql with the new contents, excluding the sections at the beginning that alter the tables.
8. Create a new database and run the new gmbuilder.sql.
9. Run GMbuilder.

**Comment by kdahlquist** [comment]
Closing as per @NAnguiano's e-mail today.

**Comment by dondi** [comment]
👍
