### ISSUE TITLE
Content missing from http://xmlpipedb.cs.lmu.edu/

### ISSUE THREAD

**Issue by kdahlquist** [lmu-bioinformatics/xmlpipedb#39]
So, I think another casualty of the server upgrade was the http://xmlpipedb.cs.lmu.edu/ page.  Right now there is no styling or content on the page.

Sorry, about this, but is there a way to get it up and running soon?

**Comment by kdahlquist** [comment]
@NAnguiano should follow instructions here: https://github.com/lmu-bioinformatics/xmlpipedb/tree/master/site to build site locally with maven.

The issue with the server is probably a server configuration issue with Apache. @dondi will look into this.

Long term we should convert to jekyll and serve on gh-pages.

**Comment by dondi** [comment]
OK, this has been addressed. As expected there was a configuration issue; upon tracking down the right settings and applying them, the content is now rendered correctly once more. No updates since 2011—has it really been that long?

**Comment by kdahlquist** [comment]
Yes, it's been that long.  Jekyll-izing it will help so I can help with editing the web site.

**Comment by kdahlquist** [comment]
Didn't get a chance to close this before.  Confirmed content is there and closing.  Created a new issue for converting the web site to Jekyll #43.
