### ISSUE TITLE
Write Documentation on Updating GMBuilder to work with new obo-xml files

### ISSUE THREAD

**Issue by NAnguiano** [lmu-bioinformatics/xmlpipedb#42]
I wrote these steps in Issue #34, but I think it can use some more formal documentation on the wiki.
1. Run xsd2db on the manually edited dtd file
2. Run godbpostprocessor.
3. Select .sql file and hbm file specified by the post processor. 
4. Build the .jar with the new sql and hbm files.
5. Replace godb.sql with the edited sql file.
6. replace godb.jar with the new jar file.
7. Copy the contents of the new godb.sql file and replace the corresponding section in gmbuilder.sql with the new contents, excluding the sections at the beginning that alter the tables.
8. Create a new database and run the new gmbuilder.sql.
9. Run GMbuilder.

**Comment by kdahlquist** [comment]
Let's remember to note the expected error, as noted by @dondi on issue #41:

Yes, this error is actually normal. The `geneontologystage` table is an intermediate table that is created during GO processing. There is code that first tries to delete a pre-existing `geneontologystage` table before running the processing routine, and on a “fresh” database that has never been processed, that table does not exist. The error you are seeing is the failure of the deletion, and is totally expected for a freshly-initialized database.

**Comment by kdahlquist** [comment]
Add to this the schema spy documentation, both doing it for GODB and UniProtDB and also writing some instructions on how to do it for the future.

**Comment by kdahlquist** [comment]
This is now on the wiki; schema spy has been broken out into its own separate issue #46.
