### ISSUE TITLE
Convert web site to Jekyll

### ISSUE THREAD

**Issue by kdahlquist** [lmu-bioinformatics/xmlpipedb#43]
@NAnguiano is already in the process of converting the web site to Jekyll.

**Comment by kdahlquist** [comment]
@NAnguiano is almost done with the XMLPipeDB site converstion to Jekyll.  We need to know whether the site will live on gh-pages or on xmlpipedb.cs.lmu.edu because there is a slight difference in what she will do based on this decision.

To my best recollection, I think we talked about putting it on gh-pages and then redirecting xmlpipedb.cs.lmu.edu to the github site, but I want @dondi to confirm this before we push anything to gh-pages.

**Comment by dondi** [comment]
Yes, I think shifting the primary hosting duties to `gh-pages` will lead to increased long-term availability for the site (DDoS attacks by IoT botnets on East coast DNS providers like Dyn notwithstanding). Changing xmlpipedb.cs.lmu.edu into a redirect will preserve the original URL and we can keep that redirect permanently.

So with `gh-pages` as the main hosting site, we first need to make a decision:
1. Continue to keep our source files on `master` and use a feature called `git subtree push` to send those files to `gh-pages` whenever we want to publish new changes to our site, or…
2. Transfer our main copy of the site source files directly to the `gh-pages` branch. This will eliminate the need for a `git subtree push`. To avoid confusion, if we go this route, we should also delete the site source files from the `master` branch.

There is also a hybrid option where, for faster initial transition, we go with option 1 first, then when things are stable, we move to option 2, shifting revisions directly to the `gh-pages` branch and deleting the source files from mater.

Thinking further as I write this, I find myself leaning toward the hybrid option. I will need to show @NAnguiano how to do a subtree push, or she can look it up on the web initially and I can vet what she found.

**Comment by kdahlquist** [comment]
Sounds good.  As long as we end up with a gh-pages branch in the end, I'm happy.  That way, I'll be able to help with the maintenance of the content using the method I already do on GRNsight and GRNmap.

**Comment by dondi** [comment]
From what I can tell of the code structure, this is the command that @NAnguiano should run to push the code in `master` onto `gh-pages`:

    git subtree push --prefix site/jekyll origin gh-pages

(do this from the top of the repository clone) Upon doing this, you can check the `gh-pages` branch from the GitHub website to see if the files look right. Then of course the final test is to see if http://lmu-bioinformatics.github.io/xmlpipedb shows the site.

**Comment by NAnguiano** [comment]
That command worked! The site is now live at http://lmu-bioinformatics.github.io/xmlpipedb/ 
I've fixed the majority of the links. The site should be fully functional.

**Comment by kdahlquist** [comment]
Site is there!

We need to convert all the links that are currently pointing to SourceForge to GitHub.  Except for the wiki.  Since the wiki has a lot of documentation on it, and GitHub doesn't have a good one.  Our future plan is to migrate the SourceForge wiki content over to a CS server, but we haven't done it yet.
