### ISSUE TITLE
Run SchemaSpy and Write Documentation on how to run it

### ISSUE THREAD

**Issue by NAnguiano** [lmu-bioinformatics/xmlpipedb#46]
See title. Run SchemaSpy and write up documentation on  how to run it in the future. Also, put schemaspy results on the website.

**Comment by kdahlquist** [comment]
@NAnguiano had a breakthrough with SchemaSpy where she had to add it to the path variable (their GUI option did not work).  So, she got it to work and is pretty-ing up the documentation after this meeting.

When she's done, she can close this issue.
